site_name: STV Blog
site_url: https://saeedtaghavi.github.io/blog/

nav:
  - About me: https://saeedtaghavi.github.io
  - Blog: index.md

extra:
  social:
    - icon: material/web
      link: https://saeedtaghavi.github.io
      name: Personal website
    - icon: material/email
      link: mailto:saeed.taghavi.v@gmail.com
      name: Email
    - icon: material/linkedin
      link: https://www.linkedin.com/in/saeed-taghavi-a16488130/
      name: LinkedIn
    - icon: simple/x
      link: https://x.com/SaeedTaghaviV
      name: X (Twitter)
    - icon: material/youtube
      link: https://www.youtube.com/@saeedtaghavi7209
      name: YouTube
    - icon: material/github
      link: https://github.com/saeedtaghavi
      name: GitHub

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - blog:
      blog_dir: .
      post_dir: blog/posts
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - footnotes

  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
